import { ExternalLink } from "lucide-react";
import type { EvidenceItem, TaskContextPayload } from "@/lib/cortex-api";

export function EvidenceInspector({ context, traceId }: { context: TaskContextPayload; traceId: string }) {
  return <div className="space-y-4">
    <section className="cortex-panel p-4"><h2 className="text-sm font-semibold">Pack provenance</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Coverage</dt><dd className="mt-1">{context.source_coverage.providers_returned.join(", ") || "No providers returned"} / {context.source_coverage.providers_requested.join(", ") || "No providers requested"}</dd></div><div><dt className="text-xs text-muted-foreground">Freshness</dt><dd className="mt-1">{context.freshness.status}{context.freshness.oldest_sync_at ? ` · oldest sync ${context.freshness.oldest_sync_at}` : ""}</dd></div><div><dt className="text-xs text-muted-foreground">Retrieval path</dt><dd className="mt-1">{context.retrieval.status} · lexical {context.retrieval.lexical_candidate_count}, vector {context.retrieval.vector_candidate_count}</dd></div><div><dt className="text-xs text-muted-foreground">Trace ID</dt><dd className="mt-1 break-all font-mono text-xs">{traceId}</dd></div></dl>{context.retrieval.partial_reasons.length > 0 && <p className="mt-3 rounded border border-amber-400/30 bg-amber-400/10 p-3 text-sm">Partial reasons: {context.retrieval.partial_reasons.join(", ")}</p>}{context.missing_context.length > 0 && <p className="mt-3 rounded border border-border p-3 text-sm">Missing context: {context.missing_context.map(String).join(", ")}</p>}</section>
    <section className="space-y-3"><h2 className="text-sm font-semibold">Cited evidence</h2>{context.evidence_items.length ? context.evidence_items.map((item) => <EvidenceItemCard item={item} key={item.citation_id} />) : <div className="cortex-panel p-4 text-sm text-muted-foreground">No authorized evidence items were returned.</div>}</section>
  </div>;
}

function EvidenceItemCard({ item }: { item: EvidenceItem }) {
  return <article className="cortex-panel p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-xs text-muted-foreground">{item.provider} · {item.source_type}</p><h3 className="mt-1 text-sm font-semibold">{item.label ?? "Untitled evidence"}</h3></div>{item.citation_url && <a aria-label={`Open citation ${item.citation_id}`} className="text-cortex-blue" href={item.citation_url} rel="noreferrer" target="_blank"><ExternalLink className="size-4" /></a>}</div><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.snippet}</p><dl className="mt-4 grid gap-2 border-t border-border pt-3 font-mono text-[11px] text-muted-foreground sm:grid-cols-2"><div>citation {item.citation_id}</div><div>freshness {item.freshness}</div><div>source updated {item.source_updated_at ?? "unknown"}</div><div>last synced {item.last_synced_at ?? "unknown"}</div><div>paths {item.retrieval_paths.join(", ")}</div><div>version {item.source_version ?? "unknown"}</div><div className="break-all sm:col-span-2">hash {item.content_hash ?? "unknown"}</div></dl></article>;
}
